export const testCatalog = [
  {
    id: "fnd-acc-001",
    title: "Foundation Accounting Basics",
    level: "Foundation",
    difficulty: "easy",
    duration: 30,
    passingMarks: 24,
    totalMarks: 40,
    subject: "Accounts",
    questions: [
      {
        id: "q-fnd-1",
        question: "What is the accounting equation?",
        options: [
          "Assets = Liabilities + Capital",
          "Assets = Income - Expense",
          "Capital = Assets + Liabilities",
          "Assets = Liabilities - Capital",
        ],
        correctAnswer: 0,
        difficulty: "easy",
        explanation: "The fundamental equation is Assets = Liabilities + Owner's Equity (Capital).",
      },
      {
        id: "q-fnd-2",
        question: "Purchase of furniture for cash will:",
        options: [
          "Increase assets and decrease assets",
          "Increase liabilities",
          "Decrease capital",
          "Increase income",
        ],
        correctAnswer: 0,
        difficulty: "easy",
        explanation: "Cash decreases and furniture increases, both are assets.",
      },
      {
        id: "q-fnd-3",
        question: "Which account is a nominal account?",
        options: ["Cash", "Rent", "Debtors", "Plant"],
        correctAnswer: 1,
        difficulty: "easy",
        explanation: "Rent is an expense account and falls under nominal accounts.",
      },
      {
        id: "q-fnd-4",
        question: "A trial balance checks:",
        options: [
          "Arithmetical accuracy of ledger posting",
          "Profitability",
          "Cash balance",
          "Inventory valuation",
        ],
        correctAnswer: 0,
        difficulty: "medium",
        explanation: "It ensures total debits and credits are arithmetically equal.",
      },
    ],
  },
  {
    id: "int-tax-001",
    title: "Intermediate Taxation Drill",
    level: "Intermediate",
    difficulty: "medium",
    duration: 45,
    passingMarks: 30,
    totalMarks: 50,
    subject: "Tax",
    questions: [
      {
        id: "q-int-1",
        question: "Income under salary is taxable on:",
        options: ["Accrual or receipt basis whichever earlier", "Receipt basis only", "Accrual basis only", "Cash basis"],
        correctAnswer: 0,
        difficulty: "medium",
        explanation: "Salary is generally taxable on due or receipt basis whichever is earlier.",
      },
      {
        id: "q-int-2",
        question: "Which ITR is generally used by individuals with business income?",
        options: ["ITR-1", "ITR-2", "ITR-3", "ITR-4 only"],
        correctAnswer: 2,
        difficulty: "medium",
        explanation: "ITR-3 is used by individuals/HUFs having income from business/profession.",
      },
      {
        id: "q-int-3",
        question: "GST is a:",
        options: ["Direct tax", "Indirect tax", "Wealth tax", "Surcharge"],
        correctAnswer: 1,
        difficulty: "easy",
        explanation: "GST is an indirect, destination-based tax on supply of goods and services.",
      },
      {
        id: "q-int-4",
        question: "Input tax credit can be claimed when:",
        options: [
          "Supplier has uploaded invoice and recipient has eligible usage",
          "Cash is paid regardless of invoice",
          "Only at year-end",
          "Never for goods",
        ],
        correctAnswer: 0,
        difficulty: "hard",
        explanation: "ITC requires fulfillment of conditions including valid invoice and eligible business use.",
      },
      {
        id: "q-int-5",
        question: "Advance tax is generally paid in:",
        options: ["Single installment in March", "Quarterly installments", "Monthly installments", "No installments"],
        correctAnswer: 1,
        difficulty: "medium",
        explanation: "Advance tax is paid in specified installments during the financial year.",
      },
    ],
  },
  {
    id: "fin-audit-001",
    title: "Final Audit Challenge",
    level: "Final",
    difficulty: "hard",
    duration: 60,
    passingMarks: 36,
    totalMarks: 60,
    subject: "Audit",
    questions: [
      {
        id: "q-fin-1",
        question: "Audit risk is composed of:",
        options: [
          "Inherent risk, control risk, detection risk",
          "Business risk and market risk",
          "Financial risk and compliance risk",
          "Sampling risk only",
        ],
        correctAnswer: 0,
        difficulty: "hard",
        explanation: "As per standards, AR = IR x CR x DR.",
      },
      {
        id: "q-fin-2",
        question: "SA 700 deals with:",
        options: [
          "Forming an opinion and reporting on financial statements",
          "Audit documentation",
          "Fraud responsibilities",
          "Internal controls",
        ],
        correctAnswer: 0,
        difficulty: "hard",
        explanation: "SA 700 covers forming opinion and auditor reporting.",
      },
      {
        id: "q-fin-3",
        question: "Professional skepticism means:",
        options: [
          "Questioning mind and critical assessment of evidence",
          "Rejecting all management evidence",
          "Relying solely on prior year audit",
          "Ignoring contradictory information",
        ],
        correctAnswer: 0,
        difficulty: "medium",
        explanation: "It is an attitude that includes a questioning mind and alertness.",
      },
      {
        id: "q-fin-4",
        question: "A modified opinion can be:",
        options: ["Qualified, adverse, disclaimer", "Only qualified", "Only disclaimer", "Emphasis paragraph only"],
        correctAnswer: 0,
        difficulty: "hard",
        explanation: "Modified opinions include qualified, adverse, and disclaimer.",
      },
      {
        id: "q-fin-5",
        question: "Audit evidence should be:",
        options: ["Sufficient and appropriate", "Only verbal", "Only documentary", "Only external"],
        correctAnswer: 0,
        difficulty: "medium",
        explanation: "SA 500 requires sufficient appropriate audit evidence.",
      },
      {
        id: "q-fin-6",
        question: "Which is not a type of audit procedure?",
        options: ["Inspection", "Observation", "Valuation reserve", "Analytical procedures"],
        correctAnswer: 2,
        difficulty: "hard",
        explanation: "Valuation reserve is an accounting concept, not an audit procedure.",
      },
    ],
  },
];

export const materialsCatalog = [
  {
    id: "mat-acc-001",
    level: "Foundation",
    type: "PDF",
    title: "Accounting Fundamentals Handbook",
    description: "Core journal, ledger, trial balance and final accounts concepts with solved examples.",
    pages: 126,
    fileSize: "8.2 MB",
    progress: 42,
    downloads: 14320,
    rating: 4.7,
    subject: { name: "Accounts", color: "#6366f1" },
  },
  {
    id: "mat-law-001",
    level: "Intermediate",
    type: "PDF",
    title: "Corporate & Business Law Notes",
    description: "Exam-focused summaries with section references and memory aids.",
    pages: 184,
    fileSize: "12.5 MB",
    progress: 15,
    downloads: 12190,
    rating: 4.5,
    subject: { name: "Law", color: "#8b5cf6" },
  },
  {
    id: "mat-tax-001",
    level: "Intermediate",
    type: "PDF",
    title: "Direct Tax Fast Revision",
    description: "Updated tax rates, deduction charts, and practical question sets.",
    pages: 212,
    fileSize: "15.1 MB",
    progress: 0,
    downloads: 9870,
    rating: 4.6,
    subject: { name: "Tax", color: "#10b981" },
  },
  {
    id: "mat-audit-001",
    level: "Final",
    type: "PDF",
    title: "Advanced Auditing Master Notes",
    description: "SA-wise compact notes, reporting formats and frequently tested points.",
    pages: 240,
    fileSize: "17.4 MB",
    progress: 58,
    downloads: 7654,
    rating: 4.8,
    subject: { name: "Audit", color: "#f59e0b" },
  },
];

export const tutorSuggestions = [
  "Explain AS 10 in simple words",
  "Difference between direct and indirect taxes",
  "How to solve partnership adjustments quickly?",
  "Give me a 7-day revision plan for Final Audit",
  "Explain GST input tax credit conditions",
  "How to improve mock test score from 55% to 70%?",
];
